server:
  port: ${PORT:8085}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  frontend-url: ${FRONTEND_URL}
# =========================
# SENDGRID (thay cho SMTP Gmail)
# =========================
sendgrid:
  api:
    key: ${SENDGRID_API_KEY}
  from:
    email: ${SENDGRID_FROM_EMAIL}
    name: ${SENDGRID_FROM_NAME}

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}

# =========================
# VNPAY
# =========================

vnpay:
  tmnCode: ${VNPAY_TMN_CODE}
  hashSecret: ${VNPAY_HASH_SECRET}
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: https://endearing-empathy-production-db34.up.railway.app/api/payment/vnpay-return

# =========================
# Cloudinary
# =========================
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
